
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Apps/CLion/CLion/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
